package com.example.mindmatrix.ui

import androidx.compose.runtime.compositionLocalOf

data class AppStrings(
    val appName: String,
    val collectiveStock: String,
    val totalCollectiveStock: String,
    val fromEntries: String,
    val addHarvest: String,
    val history: String,
    val gradingGuide: String,
    val calculator: String,
    val name: String,
    val email: String,
    val location: String,
    val welcome: String,
    val selectLanguage: String,
    val saveHarvest: String,
    val quantity: String,
    val floralSource: String,
    val grade: String,
    val sustainableHarvest: String,
    val sustainableGuideTitle: String,
    val sustainableGuide1: String,
    val sustainableGuide2: String,
    val sustainableGuide3: String,
    val moistureContent: String,
    val hiveId: String,
    val batchId: String,
    val notes: String,
    val harvestDate: String,
    val estimateEarnings: String,
    val pricePerKg: String,
    val processingCosts: String,
    val estimatedProfit: String,
    val marketPrices: String,
    val gradeAPremium: String,
    val gradeBStandard: String,
    val gradeCCommercial: String,
    val gradeADesc: String,
    val gradeBDesc: String,
    val gradeCDesc: String,
    val howToTestMoisture: String,
    val moistureTestDesc: String,
    val sustainableImportance: String,
    val sustainableLivelihood: String,
    val floralCoffee: String,
    val floralWildflower: String,
    val floralForest: String,
    val floralMultifloral: String,
    val floralAcacia: String,
    val selectFloralSource: String,
    val harvestHistory: String,
    val qualityGuide: String,
    val standardGrading: String,
    val gradingSubtitle: String,
    val honeyColorGuide: String,
    val lightAmber: String,
    val amber: String,
    val darkAmber: String,
    val moistureTest: String,
    val spoonDropTitle: String,
    val spoonDropDesc: String,
    val thumbTestTitle: String,
    val thumbTestDesc: String,
    val waterGlassTitle: String,
    val waterGlassDesc: String,
    val selectGrade: String,
    val confirmSelection: String,
    val priceMonitor: String,
    val seasonalYield: String,
    val totalHarvest: String,
    val trackSeasonalLogs: String,
    val seasonalGoalAchieved: String,
    val charts: String,
    val floralSourceBreakdown: String,
    val viewDetailedCharts: String,
    val totalKgs: String,
    val exportToCsv: String,
    val colorAnalyzer: String,
    val colorAnalyzerDesc: String,
    val uploadImage: String,
    val suggestedGrade: String,
    val analyzing: String
)

val EnglishStrings = AppStrings(
    appName = "Jenu-Gumpu",
    collectiveStock = "Honey Producer's Collective",
    totalCollectiveStock = "Total Collective Stock",
    fromEntries = "from %d entries",
    addHarvest = "Add Harvest",
    history = "History",
    gradingGuide = "Grading Guide",
    calculator = "Calculator",
    name = "Full Name",
    email = "Email Address",
    location = "Location",
    welcome = "Welcome to Jenu-Gumpu",
    selectLanguage = "Please select your language",
    saveHarvest = "Save Harvest",
    quantity = "Quantity (kg)",
    floralSource = "Floral Source",
    grade = "Grade",
    sustainableHarvest = "Sustainable Harvest",
    sustainableGuideTitle = "Honey Harvesting Guidelines",
    sustainableGuide1 = "1. Harvest only from ripe honeycombs (sealed with wax).",
    sustainableGuide2 = "2. Leave enough honey for the bee colony to survive.",
    sustainableGuide3 = "3. Use gentle smoke; never use fire or chemicals that kill bees.",
    moistureContent = "Moisture Content (%)",
    hiveId = "Hive ID",
    batchId = "Batch ID",
    notes = "Notes/Remarks",
    harvestDate = "Harvest Date",
    estimateEarnings = "Estimate your earnings",
    pricePerKg = "Price per kg (₹)",
    processingCosts = "Processing/Transport Costs (₹)",
    estimatedProfit = "Your Estimated Profit",
    marketPrices = "Reference Market Prices",
    gradeAPremium = "Grade A",
    gradeBStandard = "Grade B",
    gradeCCommercial = "Grade C",
    gradeADesc = "Moisture < 18%, No impurities, Light color",
    gradeBDesc = "Moisture 18-20%, Minor sediment, Amber color",
    gradeCDesc = "Moisture > 20%, Dark color, Higher sediment",
    howToTestMoisture = "How to Test Moisture",
    moistureTestDesc = "Use a refractometer if available. Otherwise, perform the 'Drop Test': Grade A honey should stay intact when dropped into a glass of water.",
    sustainableImportance = "Importance: Sustainable harvesting ensures that the bee population remains healthy for future seasons.",
    sustainableLivelihood = "By following these rules, you help protect the forest ecosystem and your own livelihood.",
    floralCoffee = "Coffee Blossom",
    floralWildflower = "Wildflower",
    floralForest = "Forest Honey",
    floralMultifloral = "Multifloral",
    floralAcacia = "Acacia",
    selectFloralSource = "Select Floral Source",
    harvestHistory = "Harvest History",
    qualityGuide = "Quality Guide",
    standardGrading = "Standard Grading",
    gradingSubtitle = "Assess your harvest using traditional visual and tactile methods to ensure the highest value for the collective.",
    honeyColorGuide = "Honey Color Guide",
    lightAmber = "Light Amber",
    amber = "Amber",
    darkAmber = "Dark Amber",
    moistureTest = "Moisture Test",
    spoonDropTitle = "The Spoon Drop",
    spoonDropDesc = "Scoop a small amount and let it fall. High quality honey should fold like a thick ribbon.",
    thumbTestTitle = "The Thumb Test",
    thumbTestDesc = "Place a drop on your thumb. If it stays in a solid bead and doesn't run, it is pure honey.",
    waterGlassTitle = "The Water Glass",
    waterGlassDesc = "Drop a teaspoon into water. Pure honey will sink to the bottom without dissolving immediately.",
    selectGrade = "Select Grade",
    confirmSelection = "Confirm Selection",
    priceMonitor = "Price Monitor",
    seasonalYield = "Seasonal Yield",
    totalHarvest = "Total Harvest",
    trackSeasonalLogs = "Track your seasonal honey collection logs",
    seasonalGoalAchieved = "%d%% of your seasonal goal achieved",
    charts = "Charts",
    floralSourceBreakdown = "Stock by Source",
    viewDetailedCharts = "View Detailed Charts",
    totalKgs = "Total Kgs",
    exportToCsv = "Export History (CSV)",
    colorAnalyzer = "Honey Color Analyzer",
    colorAnalyzerDesc = "Upload a photo of your honey to find the best grade based on its color.",
    uploadImage = "Upload Honey Photo",
    suggestedGrade = "Suggested Grade",
    analyzing = "Analyzing Color..."
)

val KannadaStrings = AppStrings(
    appName = "ಜೇನು-ಗುಂಪು",
    collectiveStock = "ಜೇನು ಉತ್ಪಾದಕರ ಒಕ್ಕೂಟ",
    totalCollectiveStock = "ಒಟ್ಟು ಸಂಗ್ರಹ",
    fromEntries = "%d ಎಂಟ್ರಿಗಳಿಂದ",
    addHarvest = "ಸಂಗ್ರಹ ಸೇರಿಸಿ",
    history = "ಇತಿಹಾಸ",
    gradingGuide = "ಶ್ರೇಣೀಕರಣ ಮಾರ್ಗದರ್ಶಿ",
    calculator = "ಕ್ಯಾಲ್ಕುಲೇಟರ್",
    name = "ಪೂರ್ಣ ಹೆಸರು",
    email = "ಇಮೇಲ್ ವಿಳಾಸ",
    location = "ಸ್ಥಳ",
    welcome = "ಜೇನು-ಗುಂಪುಗೆ ಸುಸ್ವಾಗತ",
    selectLanguage = "ದಯವಿಟ್ಟು ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    saveHarvest = "ಸಂಗ್ರಹ ಉಳಿಸಿ",
    quantity = "ಪ್ರಮಾಣ (ಕೆಜಿ)",
    floralSource = "ಹೂವಿನ ಮೂಲ",
    grade = "ಶ್ರೇಣಿ",
    sustainableHarvest = "ಸುಸ್ಥಿರ ಕೊಯ್ಲು",
    sustainableGuideTitle = "ಜೇನುತುಪ್ಪ ಕೊಯ್ಲು ಮಾರ್ಗಸೂಚಿಗಳು",
    sustainableGuide1 = "1. ಮಾಗಿದ ಜೇನುಗೂಡುಗಳಿಂದ ಮಾತ್ರ ಕೊಯ್ಲು ಮಾಡಿ (ಮೇಣದಿಂದ ಮುಚ್ಚಲ್ಪಟ್ಟಿದೆ).",
    sustainableGuide2 = "2. ಜೇನುನೊಣಗಳ ಬದುಕುಳಿಯಲು ಸಾಕಷ್ಟು ಜೇನುತುಪ್ಪವನ್ನು ಬಿಡಿ.",
    sustainableGuide3 = "3. ಸೌಮ್ಯವಾದ ಹೊಗೆಯನ್ನು ಬಳಸಿ; ಜೇನುನೊಣಗಳನ್ನು ಕೊಲ್ಲುವ ಬೆಂಕಿ ಅಥವಾ ರಾಸಾಯನಿಕಗಳನ್ನು ಎಂದಿಗೂ ಬಳಸಬೇಡಿ.",
    moistureContent = "ತೇವಾಂಶ (%)",
    hiveId = "ಜೇನುಗೂಡು ಸಂಖ್ಯೆ (Hive ID)",
    batchId = "ಬ್ಯಾಚ್ ಸಂಖ್ಯೆ (Batch ID)",
    notes = "ಟಿಪ್ಪಣಿಗಳು",
    harvestDate = "ಸಂಗ್ರಹ ದಿನಾಂಕ",
    estimateEarnings = "ನಿಮ್ಮ ಗಳಿಕೆಯನ್ನು ಅಂದಾಜು ಮಾಡಿ",
    pricePerKg = "ಪ್ರತಿ ಕೆಜಿ ಬೆಲೆ (₹)",
    processingCosts = "ಸಂಸ್ಕರಣೆ/ಸಾರಿಗೆ ವೆಚ್ಚಗಳು (₹)",
    estimatedProfit = "ನಿಮ್ಮ ಅಂದಾಜು ಲಾಭ",
    marketPrices = "ಉಲ್ಲೇಖಿತ ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳು",
    gradeAPremium = "ಗ್ರೇಡ್ ಎ",
    gradeBStandard = "ಗ್ರೇಡ್ ಬಿ",
    gradeCCommercial = "ಗ್ರೇಡ್ ಸಿ",
    gradeADesc = "ತೇವಾಂಶ < 18%, ಅಶುದ್ಧತೆಗಳಿಲ್ಲ, ತಿಳಿ ಬಣ್ಣ",
    gradeBDesc = "ತೇವಾಂಶ 18-20%, ಸಣ್ಣ ಕೆಸರು, ಅಂಬರ್ ಬಣ್ಣ",
    gradeCDesc = "ತೇವಾಂಶ > 20%, ಕಡು ಬಣ್ಣ, ಹೆಚ್ಚಿನ ಕೆಸರು",
    howToTestMoisture = "ತೇವಾಂಶವನ್ನು ಪರೀಕ್ಷಿಸುವುದು ಹೇಗೆ",
    moistureTestDesc = "ಲಭ್ಯವಿದ್ದರೆ ವಕ್ರೀಭವನ ಮಾಪಕವನ್ನು ಬಳಸಿ. ಇಲ್ಲದಿದ್ದರೆ, 'ಡ್ರಾಪ್ ಟೆಸ್ಟ್' ಮಾಡಿ: ಗ್ರೇಡ್ ಎ ಜೇನುತುಪ್ಪವನ್ನು ಒಂದು ಲೋಟ ನೀರಿಗೆ ಹಾಕಿದಾಗ ಅದು ಹಾಗೆಯೇ ಇರಬೇಕು.",
    sustainableImportance = "ಪ್ರಾಮುಖ್ಯತೆ: ಸುಸ್ಥಿರ ಕೊಯ್ಲು ಭವಿಷ್ಯದ ಋತುಗಳಿಗಾಗಿ ಜೇನುನೊಣಗಳ ಸಂಖ್ಯೆಯು ಆರೋಗ್ಯಕರವಾಗಿ ಉಳಿಯುವುದನ್ನು ಖಚಿತಪಡಿಸುತ್ತದೆ.",
    sustainableLivelihood = "ಈ ನಿಯಮಗಳನ್ನು ಪಾಲಿಸುವ ಮೂಲಕ, ನೀವು ಅರಣ್ಯ ಪರಿಸರ ವ್ಯವಸ್ಥೆಯನ್ನು ಮತ್ತು ನಿಮ್ಮ ಸ್ವಂತ ಜೀವನೋಪಾಯವನ್ನು ರಕ್ಷಿಸಲು ಸಹಾಯ ಮಾಡುತ್ತೀರಿ.",
    floralCoffee = "ಕಾಫಿ ಹೂವು",
    floralWildflower = "ಕಾಡುಹೂವು",
    floralForest = "ಅರಣ್ಯ ಜೇನು",
    floralMultifloral = "ವೈವಿಧ್ಯಮಯ ಹೂವು",
    floralAcacia = "ಅಕೇಶಿಯ",
    selectFloralSource = "ಹೂವಿನ ಮೂಲವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    harvestHistory = "ಸಂಗ್ರಹ ಇತಿಹಾಸ",
    qualityGuide = "ಗುಣಮಟ್ಟದ ಮಾರ್ಗದರ್ಶಿ",
    standardGrading = "ಪ್ರಮಾಣಿತ ಶ್ರೇಣೀಕರಣ",
    gradingSubtitle = "ಸಾಂಪ್ರದಾಯಿಕ ದೃಶ್ಯ ಮತ್ತು ಸ್ಪರ್ಶ ವಿಧಾನಗಳನ್ನು ಬಳಸಿಕೊಂಡು ನಿಮ್ಮ ಕೊಯ್ಲನ್ನು ಮೌಲ್ಯಮಾಪನ ಮಾಡಿ.",
    honeyColorGuide = "ಜೇನುತುಪ್ಪದ ಬಣ್ಣದ ಮಾರ್ಗದರ್ಶಿ",
    lightAmber = "ತಿಳಿ ಅಂಬರ್",
    amber = "ಅಂಬರ್",
    darkAmber = "ಕಡು ಅಂಬರ್",
    moistureTest = "ತೇವಾಂಶ ಪರೀಕ್ಷೆ",
    spoonDropTitle = "ಚಮಚದ ಹನಿ",
    spoonDropDesc = "ಸ್ವಲ್ಪ ಪ್ರಮಾಣದಲ್ಲಿ ತೆಗೆದುಕೊಂಡು ಕೆಳಗೆ ಬೀಳಲು ಬಿಡಿ. ಉತ್ತಮ ಗುಣಮಟ್ಟದ ಜೇನುತುಪ್ಪವು ದಪ್ಪ ರಿಬ್ಬನ್‌ನಂತೆ ಮಡಚಿಕೊಳ್ಳಬೇಕು.",
    thumbTestTitle = "ಹೆಬ್ಬೆರಳ ಪರೀಕ್ಷೆ",
    thumbTestDesc = "ನಿಮ್ಮ ಹೆಬ್ಬೆರಳ ಮೇಲೆ ಒಂದು ಹನಿ ಹಾಕಿ. ಅದು ಗಟ್ಟಿಯಾದ ಹನಿಯಾಗಿ ಉಳಿದು ಹರಿಯದಿದ್ದರೆ, ಅದು ಶುದ್ಧ ಜೇನುತುಪ್ಪ.",
    waterGlassTitle = "ನೀರಿನ ಲೋಟ",
    waterGlassDesc = "ಒಂದು ಟೀಚಮಚ ಜೇನುತುಪ್ಪವನ್ನು ನೀರಿಗೆ ಹಾಕಿ. ಶುದ್ಧ ಜೇನುತುಪ್ಪವು ತಕ್ಷಣ ಕರಗದೆ ಕೆಳಭಾಗಕ್ಕೆ ಸೇರುತ್ತದೆ.",
    selectGrade = "ಶ್ರೇಣಿಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    confirmSelection = "ಆಯ್ಕೆಯನ್ನು ಖಚಿತಪಡಿಸಿ",
    priceMonitor = "ಬೆಲೆ ಮಾನಿಟರ್",
    seasonalYield = "ಋತುವಿನ ಇಳುವರಿ",
    totalHarvest = "ಒಟ್ಟು ಕೊಯ್ಲು",
    trackSeasonalLogs = "ನಿಮ್ಮ ಋತುಮಾನದ ಜೇನುತುಪ್ಪ ಸಂಗ್ರಹಣೆ ದಾಖಲೆಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ",
    seasonalGoalAchieved = "ನಿಮ್ಮ ಋತುಮಾನದ ಗುರಿಯ %% %d ರಷ್ಟು ಸಾಧಿಸಲಾಗಿದೆ",
    charts = "ನಕ್ಷೆಗಳು (Charts)",
    floralSourceBreakdown = "ಮೂಲದ ಪ್ರಕಾರ ಸಂಗ್ರಹ",
    viewDetailedCharts = "ವಿವರವಾದ ನಕ್ಷೆಗಳನ್ನು ನೋಡಿ",
    totalKgs = "ಒಟ್ಟು ಕೆಜಿಗಳು",
    exportToCsv = "ಇತಿಹಾಸ ರಫ್ತು ಮಾಡಿ (CSV)",
    colorAnalyzer = "ಜೇನುತುಪ್ಪದ ಬಣ್ಣ ವಿಶ್ಲೇಷಕ",
    colorAnalyzerDesc = "ಜೇನುತುಪ್ಪದ ಬಣ್ಣದ ಆಧಾರದ ಮೇಲೆ ಉತ್ತಮ ಶ್ರೇಣಿಯನ್ನು ಕಂಡುಹಿಡಿಯಲು ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
    uploadImage = "ಜೇನುತುಪ್ಪದ ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    suggestedGrade = "ಸೂಚಿಸಲಾದ ಶ್ರೇಣಿ",
    analyzing = "ಬಣ್ಣ ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ..."
)

val LocalStrings = compositionLocalOf { EnglishStrings }
